In [3]:
import numpy as np
from scipy.sparse.linalg import svds
import matplotlib.pyplot as plt
import scipy

In [67]:
import numpy as np
from numpy import linalg
C = np.matrix([[1, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0], [1, 0, 0, 1, 1, 0], [0, 0, 0, 1, 0, 1]])
U, S, T = linalg.svd(C)
U.round(2),S.round(2),T.round(2)

(array([[ 0.44, -0.3 , -0.57,  0.58, -0.25],
        [ 0.13, -0.33,  0.59,  0.  , -0.73],
        [ 0.48, -0.51,  0.37,  0.  ,  0.61],
        [ 0.7 ,  0.35, -0.15, -0.58, -0.16],
        [ 0.26,  0.65,  0.41,  0.58,  0.09]]),
 array([2.16, 1.59, 1.28, 1.  , 0.39]),
 array([[ 0.75,  0.28,  0.2 ,  0.45,  0.33,  0.12],
        [-0.29, -0.53, -0.19,  0.63,  0.22,  0.41],
        [-0.28,  0.75, -0.45,  0.2 , -0.12,  0.33],
        [-0.  ,  0.  ,  0.58,  0.  , -0.58,  0.58],
        [ 0.53, -0.29, -0.63, -0.19, -0.41,  0.22],
        [-0.  , -0.  ,  0.  , -0.58,  0.58,  0.58]]))

(array([[ 0.4, -0.3, -0.6,  0.6, -0.2],
        [ 0.1, -0.3,  0.6,  0. , -0.7],
        [ 0.5, -0.5,  0.4,  0. ,  0.6],
        [ 0.7,  0.4, -0.2, -0.6, -0.2],
        [ 0.3,  0.6,  0.4,  0.6,  0.1]]),
 array([2.2, 1.6, 1.3, 1. , 0.4]),
 array([[ 0.7,  0.3,  0.2,  0.4,  0.3,  0.1],
        [-0.3, -0.5, -0.2,  0.6,  0.2,  0.4],
        [-0.3,  0.7, -0.4,  0.2, -0.1,  0.3],
        [-0. ,  0. ,  0.6,  0. , -0.6,  0.6],
        [ 0.5, -0.3, -0.6, -0.2, -0.4,  0.2],
        [-0. , -0. ,  0. , -0.6,  0.6,  0.6]]))

In [65]:
X

matrix([[1, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0],
        [1, 0, 0, 1, 1, 0],
        [0, 0, 0, 1, 0, 1]])